Author.create(id: 1, name: "César Aira", active: 1)
Author.create(id: 2, name: "Ricardo Andrade Millancura", active: 1)
Author.create(id: 3, name: "Dirección de Bibliotecas, Archivos y Museos", active: 1)
Author.create(id: 4, name: "Fina Calsalderrey", active: 1)
Author.create(id: 5, name: "Violeta Parra", active: 1)
Author.create(id: 6, name: "Jacqueline Balcells", active: 1)
Author.create(id: 7, name: "Ximena Milosevic Díaz", active: 1)
Author.create(id: 8, name: "Gustavo Roldán", active: 1)
Author.create(id: 9, name: "Ana María Valdés ", active: 1)
Author.create(id: 10, name: "Franz Kafka", active: 1)
Author.create(id: 11, name: "Daniel Defoe", active: 1)
Author.create(id: 12, name: "Arthur Conan Doyle", active: 1)
Author.create(id: 13, name: "Alberto Moreno", active: 1)
Author.create(id: 14, name: "Victoria Bermejo", active: 1)
Author.create(id: 15, name: "Roberto Fuentes", active: 1)
Author.create(id: 16, name: "Platón", active: 1)
Author.create(id: 17, name: "Mary W. Shelley", active: 1)
Author.create(id: 18, name: "Robin Norwood", active: 1)
Author.create(id: 19, name: "Alicia Morel", active: 1)
Author.create(id: 20, name: "Leandro Fernández de Moratín", active: 1)
Author.create(id: 21, name: "José Zorrilla", active: 1)
Author.create(id: 22, name: "Academia Chilena de Lengua Academia Brasilera de Letras ", active: 1)
Author.create(id: 23, name: "Birad RAjarm Yajnik", active: 1)
Author.create(id: 24, name: "Subsecretaria de Previsión Social", active: 1)
Author.create(id: 25, name: "Jorge Heine", active: 1)
Author.create(id: 26, name: "Academia Brasilera ", active: 1)
Author.create(id: 27, name: "Gino Sturla Zerené", active: 1)
Author.create(id: 28, name: "Christian de Montella", active: 1)
Author.create(id: 29, name: "Lata Mangeshkar- Kiran Mazumdar Shaw - Naina Lal Kidwai - Mc Mary Kom", active: 1)
Author.create(id: 30, name: "J Reyes y los niños de la Escuela Licarayén", active: 1)
Author.create(id: 31, name: "Vinicius de Moraes ", active: 1)
Author.create(id: 32, name: "Orhan Pamuk", active: 1)
Author.create(id: 33, name: "John Le Carré", active: 1)
Author.create(id: 34, name: "Victoria Bermejo y Miguel Gallardo", active: 1)
Author.create(id: 35, name: "Lynn Caine", active: 1)
Author.create(id: 36, name: "Louisa M. Alcott", active: 1)
Author.create(id: 37, name: "Mohammed Bin Rashid Al Maktoum", active: 1)
Author.create(id: 38, name: "Joaquín Machado de Assis", active: 1)
Author.create(id: 39, name: "Claudio da Costa Braga", active: 1)
Author.create(id: 40, name: "Affonso Romano de Sant'anna", active: 1)
Author.create(id: 41, name: "Manuela Gorriti", active: 1)
Author.create(id: 42, name: "Mario Levi", active: 1)
Author.create(id: 43, name: "Tuna Kiremitci", active: 1)
Author.create(id: 44, name: "Ali Ksrabayram", active: 1)
Author.create(id: 45, name: "Hasan Erkek", active: 1)
Author.create(id: 46, name: "Ayse Kulin", active: 1)
Author.create(id: 47, name: "Ahmet Ümit", active: 1)
Author.create(id: 48, name: "Orhan Kemal", active: 1)
Author.create(id: 49, name: "Perihan Magden", active: 1)
Author.create(id: 50, name: "Ricardo Andrade Millacura", active: 1)
Author.create(id: 51, name: "Jaime Eyzaguirre", active: 1)
Author.create(id: 52, name: "Robert L. Stevenson", active: 1)
Author.create(id: 53, name: "Juan Rulfo", active: 1)
Author.create(id: 54, name: "Pilar Sordo", active: 1)
Author.create(id: 55, name: "Gilberto Rondón Ortiz", active: 1)
Author.create(id: 56, name: "Gabriel García Márquez", active: 1)
Author.create(id: 57, name: "GuillerminaAltomonte", active: 1)
Author.create(id: 58, name: "Mario Puzo", active: 1)
Author.create(id: 59, name: "Paolo Lanzotti", active: 1)
Author.create(id: 60, name: "Gustavo Ferraris Del Conte", active: 1)
Author.create(id: 61, name: "Jordi Sierra i Fabra", active: 1)
Author.create(id: 62, name: "Carlos Cuauhtémoc Sánchez", active: 1)
Author.create(id: 63, name: "Pablo Simonetti", active: 1)
Author.create(id: 64, name: "Luisgé Martín", active: 1)
Author.create(id: 65, name: "Dalai Lama", active: 1)
Author.create(id: 66, name: "Luis Gastón Mora Obregón", active: 1)
Author.create(id: 67, name: "Philippe Labro", active: 1)
Author.create(id: 68, name: "Isabela Herranz", active: 1)
Author.create(id: 69, name: "P&J", active: 1)
Author.create(id: 70, name: "Francisco Coloane", active: 1)
Author.create(id: 71, name: "Julio Ramón", active: 1)
Author.create(id: 72, name: "Luis Enrique Delano", active: 1)
Author.create(id: 73, name: "Víctor Hugo de la Fuente", active: 1)
Author.create(id: 74, name: "Steven Wheeler", active: 1)
Author.create(id: 75, name: "Ministry of external affairs government of india", active: 1)
Author.create(id: 76, name: "Jorge Luis Hidalgo Castellanos", active: 1)
Author.create(id: 77, name: "Werner Forman", active: 1)
Author.create(id: 78, name: "Ashok Malik", active: 1)
Author.create(id: 79, name: "Philippe Nessmann, Peter Allen", active: 1)
Author.create(id: 80, name: "Müesser Yeniay", active: 1)
Author.create(id: 81, name: "Mehmet Murat Somer", active: 1)
Author.create(id: 82, name: "Hossein Amirsadeghi", active: 1)
Author.create(id: 83, name: "Ana María Stuven y Marco A. Pamplona", active: 1)
Author.create(id: 84, name: "Sun-me Yoon", active: 1)
Author.create(id: 85, name: "Antoine de Saint-Exupéry", active: 1)
Author.create(id: 86, name: "Ann Cameron", active: 1)
Author.create(id: 87, name: "Yolanda Reyes", active: 1)
Author.create(id: 88, name: "Oscar Wilde", active: 1)
Author.create(id: 89, name: "Saúl Schkolnik", active: 1)
Author.create(id: 90, name: "Horacio Quiroga", active: 1)
Author.create(id: 91, name: "Manuel Rojas", active: 1)
Author.create(id: 92, name: "Lucía Baquedano", active: 1)
Author.create(id: 93, name: "Juan Muñoz Martín", active: 1)
Author.create(id: 94, name: "Jorge Díaz", active: 1)
Author.create(id: 95, name: "Albert Camus", active: 1)
Author.create(id: 96, name: "Ernest Hemingway", active: 1)
Author.create(id: 97, name: "Raymond l. Bruckberger", active: 1)
Author.create(id: 98, name: "Oscar Aguiera y Joe Tonko", active: 1)
Author.create(id: 99, name: "Vida", active: 1)
Author.create(id: 100, name: "Señor Madiba", active: 1)
Author.create(id: 101, name: "Cristina de Alemdia e Souza", active: 1)
Author.create(id: 102, name: "Ximena Milosevic", active: 1)
Author.create(id: 103, name: "Embajada de Korea", active: 1)
Author.create(id: 104, name: "Embajada de Tailandia", active: 1)