Genre.create(id: 1, name: "Relatos", active: 1)
Genre.create(id: 2, name: "Novela", active: 1)
Genre.create(id: 3, name: "Informativo", active: 1)
Genre.create(id: 4, name: "Infantil", active: 1)
Genre.create(id: 5, name: "Cancionero", active: 1)
Genre.create(id: 6, name: "Historia", active: 1)
Genre.create(id: 8, name: "Poesía", active: 1)
Genre.create(id: 9, name: "Autoayuda", active: 1)
Genre.create(id: 10, name: "Filosofía ", active: 1)
Genre.create(id: 11, name: "Teatro", active: 1)
Genre.create(id: 12, name: "Dramático", active: 1)
Genre.create(id: 13, name: "Meditación", active: 1)
Genre.create(id: 14, name: "Fotografía", active: 1)
Genre.create(id: 15, name: "Cuentos", active: 1)
Genre.create(id: 16, name: "Comic", active: 1)