Publisher.create( id: 1, name: 'Cuneta', active: 1)
Publisher.create( id: 2, name: 'Hueders', active: 1)
Publisher.create( id: 3, name: 'Andres Bello', active: 1)
Publisher.create( id: 4, name: 'El barco de papel', active: 1)
Publisher.create( id: 5, name: 'Zig-Zag', active: 1)
Publisher.create( id: 6, name: 'Comuna literaria', active: 1)
Publisher.create( id: 7, name: 'La media noche del Aleph', active: 1)
Publisher.create( id: 8, name: 'Sermograf Brasil', active: 1)